// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrvecyvyomqjougfnpdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ydmVjeXZ5b21xam91Z2ZucGRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1ODY4NDQsImV4cCI6MjA2NTE2Mjg0NH0.AeNlX6ALgDvNGJI6hOlTBHh75Z8KxKstTeMSseVKod8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});